spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/csrsm/config-server/
spring.cloud.config.server.git.searchPaths=F:\just-test
spring.cloud.config.label=master
spring.cloud.config.server.git.username=your username
spring.cloud.config.server.git.password=your password